name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.r == 'devel' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release']
        include:
          - os: ubuntu-latest
            r: 'devel'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Set up Rtools (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: r-lib/actions/setup-rtools@v2

      - name: Install system dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends pkg-config cmake libeigen3-dev

      - name: Install system dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install cmake eigen

      - name: Install system dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-eigen3 mingw-w64-ucrt-x86_64-cmake
        shell: bash

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::remotes
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: '"--no-manual"'


